function p6_0 = func_p6_0(q1,q2,q3,q4,q5,a2,d4,d6)
%FUNC_P6_0
%    P6_0 = FUNC_P6_0(Q1,Q2,Q3,Q4,Q5,A2,D4,D6)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    31-Aug-2020 22:06:41

t2 = q2+q3;
t3 = sin(q5);
t4 = sin(t2);
t5 = cos(q1);
t6 = sin(q1);
t7 = cos(q5);
t8 = t4.*t7;
t9 = cos(t2);
t10 = cos(q4);
t11 = t3.*t9.*t10;
t12 = t8+t11;
t13 = sin(q4);
t14 = cos(q2);
p6_0 = [d6.*(t5.*t12+t3.*t6.*t13)+a2.*t5.*t14+d4.*t4.*t5;d6.*(t6.*t12-t3.*t5.*t13)+a2.*t6.*t14+d4.*t4.*t6;-d6.*(t7.*t9-t3.*t4.*t10)-d4.*t9+a2.*sin(q2)];
