function J6_0 = func_J6_0(q1,q2,q3,q4,q5)
%FUNC_J6_0
%    J6_0 = FUNC_J6_0(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Sep-2020 16:59:54

t2 = sin(q1);
t3 = q2+q3;
t4 = sin(t3);
t5 = sin(q5);
t6 = cos(q1);
t7 = cos(t3);
t8 = cos(q5);
t9 = cos(q4);
t10 = t7.*t8;
t20 = t4.*t5.*t9;
t11 = t10-t20;
t12 = t6.*t11.*1.3e2;
t13 = t6.*t7.*1.6e2;
t14 = sin(q4);
t15 = cos(q2);
t16 = t4.*t8;
t17 = t5.*t7.*t9;
t18 = t16+t17;
t19 = sin(q2);
t21 = t2.*t11.*1.3e2;
t22 = t2.*t7.*1.6e2;
t23 = t4.*t5;
t24 = t23-t7.*t8.*t9;
t25 = t4.*1.6e2;
t26 = t4.*t8.*1.3e2;
t27 = t5.*t7.*t9.*1.3e2;
J6_0 = reshape([t2.*t4.*-1.6e2-t2.*t15.*1.3e2-t2.*t18.*1.3e2+t5.*t6.*t14.*1.3e2,t4.*t6.*1.6e2+t6.*t15.*1.3e2+t6.*t18.*1.3e2+t2.*t5.*t14.*1.3e2,0.0,t12+t13-t6.*t19.*1.3e2,t21+t22-t2.*t19.*1.3e2,t15.*1.3e2+t25+t26+t27,t12+t13,t21+t22,t25+t26+t27,t2.*t5.*t9.*1.3e2-t5.*t6.*t7.*t14.*1.3e2,t5.*t6.*t9.*-1.3e2-t2.*t5.*t7.*t14.*1.3e2,t4.*t5.*t14.*-1.3e2,t6.*t24.*-1.3e2+t2.*t8.*t14.*1.3e2,t2.*t24.*-1.3e2-t6.*t8.*t14.*1.3e2,t5.*t7.*1.3e2+t4.*t8.*t9.*1.3e2,0.0,0.0,0.0],[3,6]);
