function p6_0 = func_p6_0(q1,q2,q3,q4,q5)
%FUNC_P6_0
%    P6_0 = FUNC_P6_0(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Aug-2020 17:45:11

t2 = cos(q1);
t3 = q2+q3;
t4 = sin(t3);
t5 = sin(q5);
t6 = cos(q2);
t7 = sin(q1);
t8 = cos(q5);
t9 = t4.*t8;
t10 = cos(t3);
t11 = cos(q4);
t12 = t5.*t10.*t11;
t13 = t9+t12;
t14 = sin(q4);
p6_0 = [t2.*t4.*1.6e2+t2.*t6.*1.3e2+t2.*t13.*1.3e2+t5.*t7.*t14.*1.3e2;t4.*t7.*1.6e2+t6.*t7.*1.3e2+t7.*t13.*1.3e2-t2.*t5.*t14.*1.3e2;t10.*-1.6e2+sin(q2).*1.3e2-t8.*t10.*1.3e2+t4.*t5.*t11.*1.3e2];
